# Generated by Django 5.0 on 2023-12-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
