# Generated by Django 5.0 on 2023-12-18 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_remove_patient_telecom_system_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
